root: true
env:
  node: true
  jest: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  project: tsconfig.json
  sourceType: 'module'
plugins:
  - '@typescript-eslint/eslint-plugin'
rules:
  '@typescript-eslint/naming-convention':
    - error
  '@typescript-eslint/no-unused-vars':
    - warn
    - argsIgnorePattern: "^_"
  no-console:
    - warn
  eqeqeq:
    - error
  prettier/prettier:
    - error
